in-defense-of-global-state:
  date: 2013-04-23 11:49:00 -0800
  title: In defense of global state
  published: true

people-are-not-resources:
  date: 2013-04-17 17:36:00 -0800
  title: People are not resources
  published: true

dreamers-and-doers:
  date: 2013-04-15
  title: Dreamers and doers
  published: false

paradoxes-in-the-software-world:
  date: 2013-04-15
  title: Paradoxes in the software world
  published: false

risk-aversion-and-software-development:
  date: 2013-04-11 18:17:00 -0800
  title: Risk aversion and software development
  published: true

charts-made-dead-simple-with-hightables:
  date: 2013-04-10 07:34:00 -0800
  title: Charts made dead simple with HighTables
  published: true

swing-of-the-pendulum:
  date: 2013-04-08
  title: The swing of the pendulum
  published: false

am-i-an-engineer:
  date: 2013-04-03 12:18:00 -0800
  title: Am I an engineer?
  published: true

automating-yourself:
  date: 2013-02-28 06:53:00 -0800
  title: Automating yourself
  published: true

your-brain-is-a-liability:
  date: 2013-02-08 22:11:00 -0800
  title: Your brain is a liability
  published: true

unbreaking-datamapper:
  date: 2013-01-29 23:21:00 -0800
  title: Unbreaking DataMapper
  published: true

making-yaml-safe-again:
  date: 2013-01-24
  title: Making YAML safe again
  published: true

ab-testing-and-irreducible-complexity:
  date: 2013-01-13
  title: A/B testing and irreducible complexity
  published: true

optimize-for-comprehensibility:
  date: 2012-12-29
  title: Optimize for comprehensibility
  published: true

universe-is-a-one-way-function:
  date: 2012-10-03
  title: The universe is a one-way function
  published: true

cannibalizing-yourself-on-purpose:
  date: 2012-09-24
  title: Cannibalizing yourself on purpose
  published: true

brushing-up-on-cs-part-1-algorithmic-complexity:
  date: 2012-09-15
  title: "Brushing up on C.S. - Part 1: Algorithmic Complexity"
  published: true

magical-optimization-of-the-+=-operator-with-strings:
  date: 2012-08-25
  title: A magical optimization of the += operator with strings
  published: true

value-of-a-detached-perspective:
  date: 2012-08-21
  title: The value of a detached perspective
  published: false

to-start-over-or-continue:
  date: 2012-06-15
  title: To start over or continue
  published: true

fast-string-concatenation:
  date: 2012-06-11
  title: Fast String Concatenation
  published: false

trouble-with-stop-the-line-ci:
  date: 2012-05-07
  title: The trouble with stop-the-line CI
  published: true

littlest-ruby-debugger:
  date: 2012-03-16
  title: The littlest Ruby debugger
  published: true

conflation-of-cause-and-responsibility:
  date: 2012-02-19
  title: The Conflation of Cause and Responsibility
  published: false

optimizing-mind:
  date: 2012-02-19
  title: The Optimizing Mind
  published: true

trick-to-good-ballpark-estimates:
  date: 2012-02-02
  title: The trick to good ballpark estimates
  published: true

sometimes-the-best-strategy-is-to-retreat:
  date: 2011-02-28
  title: Sometimes the best strategy is to retreat
  published: true

boy-can-dream:
  date: 2011-02-24
  title: A boy can dream...
  published: true

how-to-build-a-thread-safe-lock-free-resizable-array:
  date: 2011-02-23
  title: How to build a thread-safe lock-free resizable "array"
  published: true

am-i-being-obnoxious:
  date: 2012-01-31
  title: Am I being obnoxious?
  published: true

being-agile-with-continuous-integration:
  date: 2012-01-27
  title: Being agile with continuous integration
  published: true

ghost-clicks-in-jquery-mobile:
  date: 2011-11-01
  title: Ghost clicks in jQuery Mobile
  published: true

best-dependency-is-no-dependency:
  date: 2011-09-20
  title: The best dependency is no dependency
  published: false

were-all-going-to-die-because-you-dont-know-what-a-binary-tree-is:
  date: 2011-08-13
  title: We're all going to die because you don't know what a binary tree is
  published: false

paradox-of-free-will:
  date: 2011-07-30
  title: The paradox of free will
  published: false

does-jquery-turn-programmers-into-babies:
  date: 2011-07-29
  title: Does jQuery turn programmers into babies?
  published: false

not-solved-here-syndrome:
  date: 2011-07-24
  title: Not solved here syndrome
  published: false

acquired-needs-of-software-engineers:
  date: 2011-04-26
  title: The acquired needs of software engineers
  published: false

how-i-discovered-a-bug-in-the-csharp-compiler-part-2:
  date: 2011-04-03
  title: How I discovered a bug in the C# compiler, part 2
  published: true

how-i-discovered-a-bug-in-the-csharp-compiler-part-1:
  date: 2011-03-31
  title: How I discovered a bug in the C# compiler, part 1
  published: true

such-a-thing-as-too-much-abstraction:
  date: 2011-03-17
  title: There's such a thing as too much abstraction, you know
  published: false

how-do-you-know-something-for-sure:
  date: 2011-03-16
  title: How do you know something for sure?
  published: false

ridiculous-time-waster-that-is-code-aesthetics:
  date: 2011-03-15
  title: The ridiculous time waster that is code aesthetics
  published: false

terminating-condition:
  date: 2011-01-15
  title: "Resolution: the need for a terminating condition"
  published: true
