am-i-an-engineer:
  date: 2013-04-03 12:18:00 -0800
  title: Am I an engineer?
  published: true

automating-yourself:
  date: 2013-02-28 06:53:00 -0800
  title: Automating yourself
  published: true

your-brain-is-a-liability:
  date: 2013-02-08 22:11:00 -0800
  title: Your brain is a liability
  published: true

unbreaking-datamapper:
  date: 2013-01-29 23:21:00 -0800
  title: Unbreaking DataMapper
  published: true

making-yaml-safe-again:
  date: 2013-01-24
  title: Making YAML safe again
  published: true

ab-testing-and-irreducible-complexity:
  date: 2013-01-13
  title: A/B testing and irreducible complexity
  published: true

optimize-for-comprehensibility:
  date: 2012-12-29
  title: Optimize for comprehensibility
  published: true

universe-is-a-one-way-function:
  date: 2012-10-03
  title: The universe is a one-way function
  published: true

cannibalizing-yourself-on-purpose:
  date: 2012-09-24
  title: Cannibalizing yourself on purpose
  published: true

brushing-up-on-cs-part-1-algorithmic-complexity:
  date: 2012-09-15
  title: "Brushing up on C.S. - Part 1: Algorithmic Complexity"
  published: true

magical-optimization-of-the-+=-operator-with-strings:
  date: 2012-08-25
  title: A magical optimization of the += operator with strings
  published: true

value-of-a-detached-perspective:
  date: 2012-08-21
  title: The value of a detached perspective
  published: false

to-start-over-or-continue:
  date: 2012-06-15
  title: To start over or continue
  published: true

fast-string-concatenation:
  date: 2012-06-11
  title: Fast String Concatenation
  published: false

trouble-with-stop-the-line-ci:
  date: 2012-05-07
  title: The trouble with stop-the-line CI
  published: true

littlest-ruby-debugger:
  date: 2012-03-16
  title: The littlest Ruby debugger
  published: true

conflation-of-cause-and-responsibility:
  date: 2012-02-19
  title: The Conflation of Cause and Responsibility
  published: false

optimizing-mind:
  date: 2012-02-19
  title: The Optimizing Mind
  published: true

trick-to-good-ballpark-estimates:
  date: 2012-02-02
  title: The trick to good ballpark estimates
  published: true

am-i-being-obnoxious:
  date: 2012-02-02
  title: Am I being obnoxious?
  published: false

sometimes-the-best-strategy-is-to-retreat:
  date: 2011-02-28
  title: Sometimes the best strategy is to retreat
  published: true

boy-can-dream:
  date: 2011-02-24
  title: A boy can dream...
  published: true

how-to-build-a-thread-safe-lock-free-resizable-array:
  date: 2011-02-23
  title: How to build a thread-safe lock-free resizable "array"
  published: true

terminating-condition:
  date: 2011-01-15
  title: "Resolution: the need for a terminating condition"
  published: true
