fast-string-concatenation:
  date: 2012-08-25
  title: Fast String Concatenation
  published: true

value-of-a-detached-perspective:
  date: 2012-08-21
  title: The value of a detached perspective
  published: true

to-start-over-or-continue:
  date: 2012-06-15
  title: To start over or continue
  published: true

trouble-with-stop-the-line-ci:
  date: 2012-05-07
  title: The trouble with stop-the-line CI
  published: true

optimizing-mind:
  date: 2012-02-19
  title: The Optimizing Mind
  published: true

trick-to-good-ballpark-estimates:
  date: 2012-02-02
  title: The trick to good ballpark estimates
  published: true
