source :rubygems

# Server requirements
gem "thin"

# Project requirements
gem "rake"
gem "sinatra-flash", :require => "sinatra/flash"

# Component requirements
gem "haml"
gem "redcarpet"
gem "sass"
gem "dm-sqlite-adapter"
gem "dm-validations"
gem "dm-timestamps"
gem "dm-migrations"
gem "dm-constraints"
gem "dm-aggregates"
gem "dm-core"

# Test requirements
gem "rspec", :group => "test"
gem "rack-test", :group => "test", :require => "rack/test"

# Padrino Stable Gem
gem "padrino", "0.10.6"
