require File.join(File.dirname(__FILE__), "config", "boot")

def path_to(file)
  File.join(File.dirname(__FILE__), file)
end

namespace :db do
  desc "Migrate the database with the latest models"
  task :update do
    DataMapper.auto_migrate!
    puts "Database updated."
  end

  desc "Take all the posts in the posts/ folder and add them to the database"
  task :import_posts do
    Dir.glob("posts/*.markdown").each do |file|
      title_from_file_name = file.match(/posts\/[^\s]*\s*(.*)/)
      if title_from_file_name
        title = title_from_file_name[1].chomp(".markdown")
        content = File.read(path_to(file))
        post = Post.create(:title => title, :content => content, :last_updated => Time.now)
        puts "Created post '#{title}' (#{post.id})"
      end
    end
  end
end
