require 'find'
require 'redcarpet'
require 'wordpress'

def quit(msg)
  puts msg
  exit 1
end

def successful_wordpress_response?(response)
  return false if !(response.is_a? Hash)
  return false if !(response.include? :rsp)
  return false if !(response[:rsp].include? :stat)
  return false if response[:rsp][:stat] != "ok"
  true
end

desc "Render all posts from Markdown to HTML"
task :render_posts do
  Find.find(".").select { |f| f.end_with? "markdown" }.each do |markdown_file|
    html_file = File.join("dist", File.dirname(markdown_file) + ".html")

    STDOUT.write "Rendering #{File.basename(html_file)}... "

    File.open(html_file, "w") do |io|
      io.write Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(File.read(markdown_file))
    end
    
    puts "Done."
  end
end

desc "Upload a post to WordPress by name (tags should be a colon-delimited list)"
task :post, :title, :tags do |task, args|
  username = ENV["WORDPRESS_USERNAME"]
  quit "You must set the WORDPRESS_USERNAME environment variable" if username.nil?

  password = ENV["WORDPRESS_PASSWORD"]
  quit "You must set the WORDPRESS_PASSWORD environment variable" if password.nil?

  login_url = ENV["WORDPRESS_LOGIN_URL"]
  quit "You must set the WORDPRESS_LOGIN_URL environment variable" if login_url.nil?

  client = Wordpress::Client.new(username, password, login_url)

  title = args[:title]
  tags = args.include?(:tags) ? args[:tags].split(":") : []

  html_file = File.join("dist", "#{title}.html")
  quit "'#{title}' is not a valid post title!" if not File.exist?(html_file)

  content = File.read(html_file)

  STDOUT.write "Posting '#{title}'... "

  response = client.post(title, content, tags)

  if successful_wordpress_response?(response)
    puts "Done! Post now available at: #{response[:rsp][:post][:url]}"
  else
    puts "Failed!"
    puts ""
    puts "Message:"
    puts response[:rsp][:err][:msg]
  end
end

task :default => :render_posts